run:
  timeout: 5m
  go: '1.23'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - copyloopvar
    - durationcheck
    - errname
    - gocritic
    - gosec
    - noctx
    - prealloc
    - unconvert

linters-settings:
  gocritic:
    enabled-checks:
      - appendAssign
      - argOrder
      - badCall
      - badLock
      - caseOrder
      - dupArg
      - dupCase
      - dupSubExpr
      - flagName
      - nilValReturn
      - offBy1
      - sloppyReassign
      - truncateCmp
      - weakCond

  gosec:
    excludes:
      - G104

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
